import React, { useEffect, useState } from 'react'
import { getAlerts, createAlert, updateAlert, deleteAlert, getAlertStats } from '../api'
import { Badge, Pagination, SearchBar, Spinner, Empty, Modal, Field, CrudActions, PageHeader, Confirm, StatCard } from '../components/ui'
import { SetPageHelp } from '../components/HelpOverlay'
import { Bell, Plus, RefreshCw } from 'lucide-react'
import toast from 'react-hot-toast'

const PAGE_META = {
  title: 'Alerts',
  entities: [{
    name: 'alerts', description: 'Compliance alerts generated by the screening engine and rules',
    fields: [
      { name: 'alert_type', type: 'enum', description: 'SANCTIONS_MATCH | WATCHLIST_HIT | TRANSACTION_BLOCK | ADVERSE_MEDIA | PEP_MATCH' },
      { name: 'severity', type: 'enum', description: 'CRITICAL | HIGH | MEDIUM | LOW' },
      { name: 'status', type: 'enum', description: 'OPEN | IN_REVIEW | RESOLVED | DISMISSED' },
      { name: 'subject_name', type: 'varchar', description: 'Subject that triggered the alert' },
      { name: 'subject_type', type: 'enum', description: 'INDIVIDUAL | ENTITY | VESSEL | TRANSACTION' },
      { name: 'description', type: 'text', description: 'Alert description and context' },
      { name: 'assigned_to', type: 'varchar', description: 'Compliance officer assigned' },
      { name: 'source_list', type: 'varchar', description: 'Sanctions list that triggered the alert' },
    ]
  }]
}

const ALERT_TYPES = ['SANCTIONS_MATCH', 'WATCHLIST_HIT', 'TRANSACTION_BLOCK', 'ADVERSE_MEDIA', 'PEP_MATCH', 'MANUAL']
const SEVERITIES = ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW']
const STATUSES = ['OPEN', 'IN_REVIEW', 'RESOLVED', 'DISMISSED']

export default function Alerts() {
  const [data, setData] = useState<any[]>([])
  const [total, setTotal] = useState(0)
  const [page, setPage] = useState(1)
  const [search, setSearch] = useState('')
  const [severity, setSeverity] = useState('')
  const [status, setStatus] = useState('')
  const [loading, setLoading] = useState(false)
  const [selected, setSelected] = useState<any>(null)
  const [showForm, setShowForm] = useState(false)
  const [showDetail, setShowDetail] = useState(false)
  const [showDelete, setShowDelete] = useState(false)
  const [form, setForm] = useState<any>({})
  const [saving, setSaving] = useState(false)
  const [stats, setStats] = useState<any>({})

  const load = async () => {
    setLoading(true)
    try {
      const [r, s] = await Promise.all([
        getAlerts({ page, limit: 50, search, severity, status }),
        getAlertStats()
      ])
      setData(r.data.data || [])
      setTotal(r.data.total || 0)
      setStats(s.data || {})
    } catch (e: any) { toast.error(e.message) }
    finally { setLoading(false) }
  }

  useEffect(() => { load() }, [page, search, severity, status])

  const save = async () => {
    setSaving(true)
    try {
      if (form.id) { await updateAlert(form.id, form); toast.success('Alert updated') }
      else { await createAlert(form); toast.success('Alert created') }
      setShowForm(false); load()
    } catch (e: any) { toast.error(e.message) }
    finally { setSaving(false) }
  }

  const del = async () => {
    await deleteAlert(selected.id); toast.success('Alert deleted')
    setShowDelete(false); load()
  }

  const quickUpdate = async (id: number, newStatus: string) => {
    await updateAlert(id, { status: newStatus, resolved_at: newStatus === 'RESOLVED' ? new Date().toISOString() : null })
    toast.success(`Alert ${newStatus.toLowerCase()}`)
    load()
  }

  const f = (k: string, v: any) => setForm((p: any) => ({ ...p, [k]: v }))

  return (
    <div>
      <SetPageHelp meta={PAGE_META} />
      <PageHeader title="Alerts" subtitle="Compliance alerts and notifications" icon={Bell}
        actions={<>
          <button onClick={load} className="btn-ghost"><RefreshCw size={14} className={loading ? 'animate-spin' : ''} /></button>
          <button onClick={() => { setForm({ status: 'OPEN', severity: 'HIGH', alert_type: 'SANCTIONS_MATCH' }); setShowForm(true) }} className="btn-primary"><Plus size={14} /> New Alert</button>
        </>} />

      <div className="grid grid-cols-4 gap-4 mb-6">
        <StatCard label="Open Alerts" value={stats.open_alerts || 0} color="text-blue-400" />
        <StatCard label="Critical" value={stats.critical || 0} color="text-red-400" />
        <StatCard label="High Severity" value={stats.high_severity || 0} color="text-amber-400" />
        <StatCard label="Resolved Today" value={stats.resolved_today || 0} color="text-green-400" />
      </div>

      <div className="card mb-4">
        <div className="p-4 flex flex-wrap gap-3">
          <SearchBar value={search} onChange={(v: string) => { setSearch(v); setPage(1) }} placeholder="Search alerts..." />
          <select className="select w-40" value={severity} onChange={e => { setSeverity(e.target.value); setPage(1) }}>
            <option value="">All Severities</option>
            {SEVERITIES.map(s => <option key={s}>{s}</option>)}
          </select>
          <select className="select w-36" value={status} onChange={e => { setStatus(e.target.value); setPage(1) }}>
            <option value="">All Statuses</option>
            <option value="OPEN">Open</option>
            {STATUSES.map(s => <option key={s}>{s}</option>)}
          </select>
        </div>
      </div>

      <div className="card">
        <div className="table-wrap">
          <table className="table">
            <thead><tr><th>Type</th><th>Subject</th><th>Severity</th><th>Status</th><th>Source List</th><th>Assigned To</th><th>Created</th><th>Actions</th></tr></thead>
            <tbody>
              {loading && !data.length ? <tr><td colSpan={8} className="text-center py-12"><Spinner /></td></tr>
              : data.length === 0 ? <tr><td colSpan={8}><Empty message="No alerts found" action={<button className="btn-primary" onClick={() => { setForm({ status: 'OPEN', severity: 'HIGH' }); setShowForm(true) }}><Plus size={14} /> New Alert</button>} /></td></tr>
              : data.map((row: any) => (
                <tr key={row.id}>
                  <td>
                    <div className="text-sm font-medium text-white">{row.title || row.alert_type?.replace(/_/g,' ')}</div>
                    <div className="text-xs text-slate-500 font-mono">{row.alert_id}</div>
                  </td>
                  <td>
                    <div className="font-medium text-slate-200">{row.subject_name || '—'}</div>
                  </td>
                  <td><Badge value={row.severity} /></td>
                  <td><Badge value={row.status} /></td>
                  <td><span className="font-mono text-xs text-blue-300">{row.source_system || '—'}</span></td>
                  <td className="text-xs text-slate-400">{row.assigned_to || '—'}</td>
                  <td className="text-xs text-slate-500">{row.created_at ? new Date(row.created_at).toLocaleDateString() : '—'}</td>
                  <td>
                    <div className="flex items-center gap-1">
                      {row.status === 'OPEN' && <>
                        <button onClick={() => quickUpdate(row.id, 'RESOLVED')} className="text-xs text-green-400 hover:text-green-300 px-2 py-1 bg-green-900/20 rounded">Resolve</button>
                        <button onClick={() => quickUpdate(row.id, 'DISMISSED')} className="text-xs text-slate-400 hover:text-slate-300 px-2 py-1 bg-slate-800 rounded">Dismiss</button>
                      </>}
                      <CrudActions onView={() => { setSelected(row); setShowDetail(true) }} onEdit={() => { setForm(row); setShowForm(true) }} onDelete={() => { setSelected(row); setShowDelete(true) }} />
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        <div className="px-4 pb-4"><Pagination page={page} total={total} limit={50} onChange={setPage} /></div>
      </div>

      <Modal open={showDetail} onClose={() => setShowDetail(false)} title="Alert Detail" size="md">
        {selected && (
          <div className="p-6 space-y-3">
            {[['Type', selected.alert_type], ['Subject', selected.subject_name], ['Severity', selected.severity], ['Status', selected.status], ['Source List', selected.source_list], ['Assigned To', selected.assigned_to], ['Created', selected.created_at ? new Date(selected.created_at).toLocaleString() : '—']].map(([l, v]) => (
              <div key={l} className="flex justify-between py-2 border-b border-slate-800">
                <span className="text-xs text-slate-500">{l}</span>
                <span className="text-xs text-slate-200 font-medium">{v || '—'}</span>
              </div>
            ))}
            {selected.description && <div className="bg-slate-800/60 rounded-xl p-3 text-sm text-slate-300">{selected.description}</div>}
          </div>
        )}
      </Modal>

      <Modal open={showForm} onClose={() => setShowForm(false)} title={form.id ? 'Edit Alert' : 'New Alert'} size="lg">
        <div className="p-6 grid grid-cols-2 gap-4">
          <Field label="Alert Type"><select className="select" value={form.alert_type || ''} onChange={e => f('alert_type', e.target.value)}><option value="">Select</option>{ALERT_TYPES.map(t => <option key={t}>{t}</option>)}</select></Field>
          <Field label="Severity"><select className="select" value={form.severity || 'HIGH'} onChange={e => f('severity', e.target.value)}>{SEVERITIES.map(s => <option key={s}>{s}</option>)}</select></Field>
          <div className="col-span-2"><Field label="Subject Name" required><input className="input" value={form.subject_name || ''} onChange={e => f('subject_name', e.target.value)} /></Field></div>
          <Field label="Subject Type"><select className="select" value={form.subject_type || 'INDIVIDUAL'} onChange={e => f('subject_type', e.target.value)}><option>INDIVIDUAL</option><option>ENTITY</option><option>VESSEL</option><option>TRANSACTION</option></select></Field>
          <Field label="Status"><select className="select" value={form.status || 'OPEN'} onChange={e => f('status', e.target.value)}>{STATUSES.map(s => <option key={s}>{s}</option>)}</select></Field>
          <Field label="Source List"><input className="input" value={form.source_list || ''} onChange={e => f('source_list', e.target.value)} placeholder="e.g., OFAC" /></Field>
          <Field label="Assigned To"><input className="input" value={form.assigned_to || ''} onChange={e => f('assigned_to', e.target.value)} /></Field>
          <div className="col-span-2"><Field label="Description"><textarea className="input h-20 resize-none" value={form.description || ''} onChange={e => f('description', e.target.value)} /></Field></div>
          <div className="col-span-2 flex justify-end gap-3"><button className="btn-ghost" onClick={() => setShowForm(false)}>Cancel</button><button className="btn-primary" onClick={save} disabled={saving}>{saving ? <Spinner size={14} /> : null}{form.id ? 'Update' : 'Create'}</button></div>
        </div>
      </Modal>

      <Confirm open={showDelete} onClose={() => setShowDelete(false)} onConfirm={del} title="Delete Alert" message={`Delete this alert for "${selected?.subject_name}"?`} />
    </div>
  )
}
