import React, { useState } from 'react'
import { api } from '../api'
import { Spinner, PageHeader, Field, StatCard } from '../components/ui'
import { SetPageHelp } from '../components/HelpOverlay'
import { BarChart3, Download, RefreshCw, FileText, TrendingUp, Shield, AlertTriangle } from 'lucide-react'
import toast from 'react-hot-toast'

const PAGE_META = {
  title: 'Reports',
  entities: [{
    name: 'reports', description: 'Compliance and regulatory reports generated by the Sanctions Engine',
    fields: [
      { name: 'report_type', type: 'enum', description: 'SCREENING_SUMMARY | BLOCKED_TRANSACTIONS | CASE_STATUS | ALERT_SUMMARY | SANCTIONS_COVERAGE | AUDIT_TRAIL' },
      { name: 'date_from', type: 'date', description: 'Report start date' },
      { name: 'date_to', type: 'date', description: 'Report end date' },
      { name: 'format', type: 'enum', description: 'PDF | EXCEL | CSV | JSON' },
    ]
  }]
}

const REPORT_TYPES = [
  { id: 'screening_summary', name: 'Screening Summary', description: 'Overview of all screening activity', icon: Shield, color: 'text-blue-400' },
  { id: 'blocked_transactions', name: 'Blocked Transactions', description: 'All transactions blocked by sanctions', icon: AlertTriangle, color: 'text-red-400' },
  { id: 'case_status', name: 'Case Status Report', description: 'Open, in-review, and escalated cases', icon: FileText, color: 'text-amber-400' },
  { id: 'alert_summary', name: 'Alert Summary', description: 'Compliance alerts by severity and type', icon: AlertTriangle, color: 'text-purple-400' },
  { id: 'sanctions_coverage', name: 'Sanctions Coverage', description: 'Coverage across all sanctions lists', icon: Shield, color: 'text-green-400' },
  { id: 'customer_risk', name: 'Customer Risk Report', description: 'Customer risk ratings and KYC status', icon: TrendingUp, color: 'text-cyan-400' },
  { id: 'audit_trail', name: 'Audit Trail Report', description: 'Complete system audit trail', icon: FileText, color: 'text-slate-400' },
  { id: 'regulatory_sar', name: 'SAR Template', description: 'Suspicious Activity Report template', icon: FileText, color: 'text-red-400' },
]

export default function Reports() {
  const [dateFrom, setDateFrom] = useState(new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0])
  const [dateTo, setDateTo] = useState(new Date().toISOString().split('T')[0])
  const [format, setFormat] = useState('CSV')
  const [generating, setGenerating] = useState<string | null>(null)
  const [reportData, setReportData] = useState<any>(null)
  const [activeReport, setActiveReport] = useState<string | null>(null)

  const generateReport = async (reportId: string) => {
    setGenerating(reportId)
    setActiveReport(reportId)
    setReportData(null)
    try {
      const r = await api.get(`/reports/${reportId}`, { params: { date_from: dateFrom, date_to: dateTo, format } })
      setReportData(r.data)
      toast.success(`Report generated: ${r.data.total_records || 0} records`)
    } catch (e: any) {
      toast.error('Report generation failed: ' + e.message)
    }
    setGenerating(null)
  }

  const downloadReport = async (reportId: string) => {
    try {
      const r = await api.get(`/reports/${reportId}/download`, {
        params: { date_from: dateFrom, date_to: dateTo, format },
        responseType: 'blob'
      })
      const url = URL.createObjectURL(r.data)
      const a = document.createElement('a')
      a.href = url
      a.download = `${reportId}_${dateFrom}_${dateTo}.${format.toLowerCase()}`
      a.click()
      toast.success('Download started')
    } catch (e: any) {
      toast.error('Download failed: ' + e.message)
    }
  }

  return (
    <div>
      <SetPageHelp meta={PAGE_META} />
      <PageHeader title="Reports" subtitle="Generate compliance and regulatory reports" icon={BarChart3} />

      <div className="card mb-6">
        <div className="p-5">
          <div className="grid grid-cols-4 gap-4">
            <Field label="Date From"><input className="input" type="date" value={dateFrom} onChange={e => setDateFrom(e.target.value)} /></Field>
            <Field label="Date To"><input className="input" type="date" value={dateTo} onChange={e => setDateTo(e.target.value)} /></Field>
            <Field label="Format">
              <select className="select" value={format} onChange={e => setFormat(e.target.value)}>
                <option>CSV</option>
                <option>JSON</option>
                <option>PDF</option>
                <option>EXCEL</option>
              </select>
            </Field>
            <div className="flex items-end">
              <div className="text-xs text-slate-500 pb-2">Select a report type below to generate</div>
            </div>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
        {REPORT_TYPES.map(rt => {
          const Icon = rt.icon
          const isGenerating = generating === rt.id
          return (
            <div key={rt.id} className={`card cursor-pointer hover:border-blue-500/50 transition-colors ${activeReport === rt.id ? 'border-blue-500/50 bg-blue-900/5' : 'border-slate-700'}`}>
              <div className="p-4">
                <Icon size={20} className={`${rt.color} mb-3`} />
                <div className="font-semibold text-white text-sm mb-1">{rt.name}</div>
                <div className="text-xs text-slate-500 mb-4">{rt.description}</div>
                <div className="flex gap-2">
                  <button onClick={() => generateReport(rt.id)} disabled={isGenerating} className="btn-primary text-xs py-1 flex-1">
                    {isGenerating ? <Spinner size={12} /> : 'Generate'}
                  </button>
                  <button onClick={() => downloadReport(rt.id)} className="btn-ghost text-xs py-1 px-2" title="Download">
                    <Download size={12} />
                  </button>
                </div>
              </div>
            </div>
          )
        })}
      </div>

      {reportData && (
        <div className="card">
          <div className="card-header">
            <span className="font-semibold text-white">Report: {REPORT_TYPES.find(r => r.id === activeReport)?.name}</span>
            <span className="text-xs text-slate-500">{reportData.total_records} records · {dateFrom} to {dateTo}</span>
          </div>
          <div className="p-5">
            {reportData.summary && (
              <div className="grid grid-cols-4 gap-4 mb-6">
                {Object.entries(reportData.summary).slice(0, 8).map(([k, v]) => (
                  <StatCard key={k} label={k.replace(/_/g, ' ').toUpperCase()} value={String(v)} />
                ))}
              </div>
            )}
            {reportData.data?.length > 0 && (
              <div className="table-wrap">
                <table className="table">
                  <thead>
                    <tr>{Object.keys(reportData.data[0]).slice(0, 8).map(k => <th key={k}>{k.replace(/_/g, ' ')}</th>)}</tr>
                  </thead>
                  <tbody>
                    {reportData.data.slice(0, 50).map((row: any, i: number) => (
                      <tr key={i}>
                        {Object.values(row).slice(0, 8).map((v: any, j: number) => (
                          <td key={j} className="text-xs text-slate-300">{String(v || '—').substring(0, 60)}</td>
                        ))}
                      </tr>
                    ))}
                  </tbody>
                </table>
                {reportData.data.length > 50 && <div className="text-xs text-slate-500 text-center py-3">Showing 50 of {reportData.data.length} records. Download for full data.</div>}
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  )
}
